steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/cicd-272715/java', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','eu.gcr.io/cicd-272715/java']
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
images: ['eu.gcr.io/cicd-272715/java']